#!/usr/bin/env bash
# Your Bash script must accept 2 arguments:
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

DOMAIN="$1"
SUBDOMAIN="$2"

func () {
    if [ $# == 0 ]
    then
        echo "Usage: 0-world_wide_web DOMAIN [SUBDOMAIN]"
    elif [ -z "$2" ]
    then
        www=$( dig www."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk "/^www.$DOMAIN/ {print \$5}" )
        lb01=$( dig lb-01."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk "/^lb-01.$DOMAIN/ {print \$5}" )
        web01=$( dig web-01."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk "/^web-01.$DOMAIN/ {print \$5}" )
        web02=$( dig web-02."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk "/^web-02.$DOMAIN/ {print \$5}" )
        echo "The subdomain www is a A record and points to $www"
        echo "The subdomain lb-01 is a A record and points to $lb01"
        echo "The subdomain web-01 is a A record and points to $web01"
        echo "The subdomain web-02 is a A record and points to $web02"
    else
        DESTINATION=$( dig "$SUBDOMAIN.$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk "/^$SUBDOMAIN.$DOMAIN/ {print \$5}" )
        RECORD_TYPE=$( dig "$SUBDOMAIN.$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk "/^$SUBDOMAIN.$DOMAIN/ {print \$4}" )
        echo "The subdomain $SUBDOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
    fi
    return 0
}

func "$@"
