#!/usr/bin/env bash
# Redirect to another location

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i 's+_;+_;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}+g' /etc/nginx/sites-available/default
sudo nginx -s reload
