#!/usr/bin/env bash
# Redirect to another location

apt-get update
apt-get install nginx -y
sed -i 's+_;+_;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}+g' /etc/nginx/sites-available/default
nginx -s reload
