#!/usr/bin/env bash
# Redirect to custom 404 page

apt-get -y update
apt-get -y install nginx
ufw allow nginx 'Nginx HTTPS'
touch /usr/share/nginx/html/custom_404.html
chmod 666 /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page\n" > /usr/share/nginx/html/custom_404.html
sed -i 's+_;+_;\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t+g' /etc/nginx/sites-available/default
service nginx restart
