#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements:
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
curl -H "X-Served-By: 03-$hostname"