#!/usr/bin/env bash
# This is a Bash (init) script that manages manage_my_process script

start ()
{
    ./manage_my_process &
    sudo touch /var/run/my_process.pid
    echo $! > /var/run/my_process.pid
}

stop ()
{
    kill "$(pgrep -f manage_my_process)"
    rm -f /var/run/my_process.pid
}

restart ()
{
    stop
    start
    echo "manage_my_process restarted"
}

noarg ()
{
    echo "Usage: manage_my_process {start|stop|restart}"
}
case "$1" in
    start)
        start
        echo "manage_my_process started";;
    stop)
        stop
        echo "manage_my_process stopped";;
    restart)
        restart;;
    *)
        noarg
        exit 1;;
esac
