#!/usr/bin/env bash
# This is a Bash (init) script that manages manage_my_process script
. /lib/lsb/init-functions

start ()
{
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
}

stop ()
{
    kill "$(pgrep -f manage_my_process)"
    rm -f /var/run/my_process.pid
}

restart ()
{
    stop
    start
    echo "manage_my_process restarted"
}

noarg ()
{
    echo "Usage: manage_my_process {start|stop|restart}"
}
case "$1" in
        "start")
            start
            echo "manage_my_process started";;
        "stop")
            stop
            echo "manage_my_process stopped";;
        "restart")
            restart;;
        *)
            noarg;;
esac