#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code,
#+ and displays this data.

# Requirements:
# The exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# Example: 141 130.0.236.153 200

awk '{ print $1,$9 }' apache-access.log | sort | uniq --count | sort --reverse --numeric-sort